filebeat.config:
  modules:
    path: ${path.config}/modules.d/*.yml
    reload.enabled: false

filebeat.autodiscover:
  providers:
    - type: docker
      hints.enabled: true
      json.message.key: message
      containers.ids:
        - "${data.docker.container.id}"
      json.keys_under_root: true
      json.add_error_key: false

processors:
  - add_docker_metadata: ~           

output.elasticsearch:
  hosts: ["elasticsearch:9200"]
  pipeline: "geoip-info"
