packetbeat.interfaces.device: any
packetbeat.interfaces.type: af_packet
packetbeat.interfaces.buffer_size_mb: 100

packetbeat.flows:
  timeout: 30s
  period: 10s

packetbeat.protocols:

- type: icmp
  enabled: true

- type: dhcpv4
  ports: [67, 68]

- type: dns
  ports: [53]
  include_authorities: true
  include_additionals: true

- type: http
  ports: [80, 9200, 5601]
  hide_keywords: ["pass", "password", "passwd"]
  send_headers: ["User-Agent", "Cookie", "Set-Cookie"]
  split_cookie: true
  real_ip_header: "X-Forwarded-For"

- type: tls
  ports: [443]
  send_certificates: true
  include_raw_certificates: false
  fingerprints: [ sha1, sha256 ]

- type: pgsql
  ports: [5432]

output.elasticsearch:
  hosts: ["https://es.byappt:443"]
  pipeline: geoip-info
  ssl.certificate_authorities: ["/etc/pki/root/ca.pem"]
