# metricbeat.autodiscover:
#   providers:
#     - type: docker
#       hints.enabled: true

metricbeat.modules:
- module: postgresql
  enabled: true
  metricsets:
    # Stats about every PostgreSQL database
    - database

    # Stats about the background writer process's activity
    - bgwriter

    # Stats about every PostgreSQL process
    - activity

  period: 10s

  # The host must be passed as PostgreSQL URL. Example:
  # postgres://localhost:5432?sslmode=disable
  # The available parameters are documented here:
  # https://godoc.org/github.com/lib/pq#hdr-Connection_String_Parameters
  hosts: ["postgres://${MONITOR_USR}:${MONITOR_PWD}@postgres?sslmode=disable"]


output.elasticsearch:
  hosts: ["elasticsearch:9200"]

